FROM debian:latest
RUN apt-get update
RUN apt-get install -y \
    ca-certificates \
    curl
RUN curl -fsSL \
    https://get.docker.com \
    -o get-docker.sh
RUN sh get-docker.sh
RUN rm get-docker.sh
RUN apt-get install -y \
    docker-ce \
    docker-ce-cli \
    containerd.io \
    docker-buildx-plugin \
    docker-compose-plugin
